export { default as Login } from "./Login/index";
export { default as Signup } from "./Signup/index";
export { default as Home } from "./Home/index";
export { default as Archive } from "./Archive/index";
export { default as Tags } from "./Tags/index";
export { default as Profile } from "./Profile/index";
export { default as About } from "./About/index";
export { default as ForgotPassword } from "./ForgotPassword/index";
export { default as ResetPassword } from "./ResetPassword/index";
